site_name: Clinical Hub TangoDx
site_url: https://tango.bcehsclinicalhub.ca/
use_directory_urls: true

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
  favicon: assets/favicon.ico
  language: en
  palette: 
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.expand
  - navigation.path
  - navigation.top
  - toc.integrate

nav:
  - Home: index.md
  - Paramedic Specialists: ps/index.md
  - Secondary Triage: stc/index.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: false
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.snippets:
      check_paths: true
      base_path: docs

extra_css:
  - stylesheets/extra.css

copyright: "Internal Use Only | © 2026 BC Emergency Health Services"

extra:
  search:
    placeholder: "Search TangoPulse..."

plugins:
  - search:
      indexing: 'full'
      # This is the secret: only index the main page title (level 1)
      heading_level: 1 
  - glightbox

extra_javascript:
  - javascripts/back-to-top.js