site_name: Clinical Hub TangoPulse
site_url: https://bcehsclinicalhub.github.io/tangoBot/
use_directory_urls: false

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
  favicon: assets/logo.png
  language: en
  palette: 
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant

nav:
  - Home: index.md
  - Clinical Procedures: clinical/index.md
  - Operational Guidelines: operational/index.md
  - Safety Data Sheets: chemical/index.md

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

copyright: "Internal Use Only | © 2026 BC Emergency Health Services"

extra:
  search:
    placeholder: "Search TangoPulse..."