site_name: Clinical Hub TangoDx
site_url: https://tango.bcehsclinicalhub.ca/
use_directory_urls: true

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.tabs          # Main menu (Home, PS, STC) in the blue bar
    - navigation.tabs.sticky   # Keeps that bar at the top
    - navigation.sections      # Groups your categories correctly
    - navigation.expand
    - navigation.top           # The "Back to Top" arrow
    - navigation.breadcrumbs  # The path (Home > PS > Clinical) below the bar

nav:
  - Home: index.md
  - Paramedic Specialists: ps/index.md
  - Secondary Triage: stc/index.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: false
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
      base_path: docs

extra_css:
  - stylesheets/extra.css